### PR TITLE
Added in_check? method to Game model

### PR DESCRIPTION
**Pull request by jrbland**
Added in_check? method to Game model

### CODE REVIEW

**Comment by jrbland** [comment]
@jacobwgillespie I'm having trouble testing this locally because of issues with the valid_move method.  Am I on the right track?  Thanks!

**Comment by jacobwgillespie** [comment]
Yep, that looks exactly correct!  Looks like it should work once all the pieces have a `valid_move?` method.

**Comment by jrbland** [comment]
@zaynrahn Since you signed up for this issue as well, I wanted to make sure it looked good to you.  Thanks!

**Comment by zaynrahn** [comment]
LGTM!

**Pull request merged**
