### PR TITLE
Created Piece model

### PR DESCRIPTION
**Pull request by emestabillo**

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
This LGTM, however might you want to add `Pawn` and `Rook` as well?

**Comment by emestabillo** [comment]
Hi Jacob, Zayn and I are sharing the task 😊

**Comment by zaynrahn** [comment]
Looks good!

**Comment by jacobwgillespie** [comment]
@zaynrahn one small thing for later (which is a little different here since you're sharing a task), but the person who opened the PR should be the one to eventually click merge, just in case something breaks, that way you as a reviewer don't have to end up debugging somebody else's code in that case.  But no worries here 👍

**Comment by zaynrahn** [comment]
@jacobwgillespie oops, sorry =(

**Comment by jacobwgillespie** [comment]
No worries at all, just less you have to worry about as a PR reviewer in the future!

**Pull request merged**
