### PR TITLE
Scope game model

### PR DESCRIPTION
**Pull request by zaynrahn**
Queries the database for games that need a second player.

### CODE REVIEW

**Comment by abdullahalam** [comment]
Scope looks good, but travis-ci failed the test. please check it when you can @zaynrahn

**Comment by zaynrahn** [comment]
It's failing b/c we have yet to write the tests for the models (game, pawn, queen, rook). @abdullahalam

**Comment by jacobwgillespie** [comment]
Travis is actually failing from the Rubocop build not the Rspec one...  However this PR has a lot of code from other branches mixed into this one.  We should probably untangle this before merging so that only the scope gets merged into master...

One way to do that would be to close this PR, delete the branch, and start over on a new branch and just copy the changes from https://github.com/Knightster/chess-app/pull/41/commits/3d1acfc205ac3f6ef1469e68e12f9bbf63273147 into it.  But we could also actually clean this branch with a rebase.

@zaynrahn if you'd like, sometime tomorrow I can go over a rebase with you on Hangouts.  It's not too complicated, but it's probably best to walk through how it works if you haven't ever used that git feature before.

**Comment by zaynrahn** [comment]
@jacobwgillespie Oh I am very sorry about that. I just can't seem to be getting this git workflow thing down. And yes. PM me with a time and link to Hangouts and I will be there!

**Pull request closed without merging**
