### PR TITLE
Add the model of queen method in valid_move?

### PR DESCRIPTION
**Pull request by abdullahalam**
- Add model of queen method in valid_move?
- Add queen can move horizontally
- Add queen can move vertically
- Add queen can move diagonally
- Add queen can't move horizontally, vertically and diagonally
- Analyzes the testing of RuboCop on queen valid_move? method

### CODE REVIEW

**Comment by abdullahalam** [comment]
I have received an error messages from the rubocop testing. It mentions `Cyclomatic complexity for valid_move? is too high. [7/6]`

`def valid_move?(x,y)`

**Comment by jrbland** [comment]
@abdullahalam I had been working on this model this week and you beat me to the punch pushing it to github!  This looks good!  The difference I had was a catch for if a user tried to move a piece to the same spot it currently occupies.  So if x_position == x && y_position == y it should return false.  Did you have another idea in mind to consider this?

**Comment by jacobwgillespie** [comment]
> Cyclomatic complexity for valid_move? is too high

@abdullahalam you can probably reduce this by calling `delta_x` and `delta_y` once and saving the results to variables.  Something like:

```ruby
def valid_move?(x, y)
    return false if blocked?(x, y)

    dx = delta_x(x_position, x)
    dy = delta_y(y_position, y)

    return true if dx == dy
    return true if dx > 0 && dy.zero?
    return true if dx.zero? && dy > 0
    ...
end
```

That way it's doing less calculation and instead reusing the calculations for multiple `if` statements.

**Comment by abdullahalam** [comment]
@jrbland I found it interesting for the queen valid_move? method since I have completed the method of rook and bishop valid_move? method. The rook and bishop valid_move? method is similar to the queen valid_move? method. The queen valid_move? method can move horizontally, vertically, and diagonally. I had the concept of understanding how it will work.

**Comment by abdullahalam** [comment]
@jacobwgillespie I have modified the code you instructed me and the test isn't passed it due to `Cyclomatic complexity for valid_move? is too high` 

The testing of rubocop `def valid_move?(x, y)` showed me that `def` is `Cyclomatic complexity is too high`

**Comment by abdullahalam** [comment]
When I checked on the pull request #69 and I added .rubocop.yml file. Finally, it works testing now and big thanks to @jacobwgillespie & @4Chazz

**Pull request merged**
