### PR TITLE
Game model

### PR DESCRIPTION
**Pull request by emestabillo**
Edited games controller
Added columns for the games table and ran the migration

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
For resolving merge conflicts specifically in `db/schema.rb`, you can actually just let Rails recreate the file rather than manually having to edit it.  You'd do something like:

```bash
$ git checkout game_model
$ git pull origin master # it should complain about merge conflicts and ask you to fix
$ rails db:migrate # will also recreate the db/schema.rb file
$ git commit # should open an editor with a pre-filled commit message - you can just exit the editor and it will use the default
$ git push origin game_model
```

**Comment by emestabillo** [comment]
I was wondering about that. I initially tried to drop the database and recreate..didn't work. 
When I did the commit using your instructions, an editor didn't pop up. Is this a problem?
Thanks Jacob!

**Comment by jacobwgillespie** [comment]
It's not a problem - if you pass the `-m 'message'` it won't pop up the editor 👍

**Comment by 4Chazz** [comment]
Hi Jacob, I don't think this branch has been approved yet for me to merge.  Will you take a minute and review this.  I made changes to the Games Controller - the create and game_params to be specific.
Thanks,

**Pull request merged**
