### PR TITLE
Initial commit for checkmate? method

### PR DESCRIPTION
**Pull request by jrbland**

### CODE REVIEW

**Comment by emestabillo** [comment]
@zaynrahn I used this last time: http://gitforteams.com/resources/rebasing.html 
Scroll down to Mid-Rebase Conflict from a Single File Merge Conflict
Let me know if you need help 👍

**Comment by zaynrahn** [comment]
@emestabillo Thank you so much for the reference!

**Comment by jacobwgillespie** [comment]
What's the status of this PR?  Is it ready for code review yet?

**Comment by jrbland** [comment]
@zaynrahn I want to say you are still working on a method for this pull request.  Is that right?

**Comment by zaynrahn** [comment]
@jrbland @jacobwgillespie Yes I am still working on it guys

**Comment by jacobwgillespie** [comment]
Replaced by #90

**Pull request closed without merging**
